### ISSUE TITLE
Grid is giving me a brain aneurysm, please fix the flashing light

### ISSUE THREAD

**Issue by kbooom1273** [carboncopies/BrainGenix-ERS#68] opened 2022-03-05 08:19 UTC
I open the editor and the grid is straight tripping, bugging on god. The grid hurt to look and ruins all work flow.
![Screenshot from 2022-03-05 00-17-12](https://user-images.githubusercontent.com/96459055/156875035-f3d5650c-c5d0-4ec7-85f7-5a926e10a42d.png)

**Comment by datacrystals** [comment] 2022-03-05 08:25
I'm sorry to hear that you're experiencing this issue. What GPU are you using?

**Comment by kbooom1273** [comment] 2022-03-05 08:27
Intel 10750h dedicated graphics, unbuntu 18.04, most recent drivers

**Comment by datacrystals** [comment] 2022-03-05 08:29
Would you mind providing the specific model and driver version that you're using?

**Comment by kbooom1273** [comment] 2022-03-05 08:30
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |

**Comment by datacrystals** [comment] 2022-03-05 08:32
Alright, i'll see if i can reproduce this. What steps did you follow to create the issue?

**Comment by kbooom1273** [comment] 2022-03-05 08:37
1.press power button
2. press f11  and select unbuntu
3. sign in
4. ctrl+alt+t
5. cd BrainGenix-ERS
6. git pull
7. cd Tools
8. bash Build.sh
9. it opens and gives me head pain

**Comment by datacrystals** [comment] 2022-03-05 08:38
Hmm, perhaps I didn't specify enough. Would you mind clarifying step number nine? That's the part where I need more info to reproduce the specific issue.

**Comment by kbooom1273** [comment] 2022-03-05 08:48
Ok, here is vide

https://user-images.githubusercontent.com/96459055/156875872-162fc342-7fcc-4d95-9d2f-105e44918b70.mp4

**Comment by datacrystals** [comment] 2022-03-05 08:56
Alright, thanks for the info. I've been unable to reproduce this exact issue on my machine. I'm using the following GPU/Driver so perhaps we can find some differences? I suspect it's due to the driver as the shaders are compiled at runtime, so any differences might cause this. 

Anyway, here's what it looks like for me when I followed the same procedure:
![image](https://user-images.githubusercontent.com/49183477/156876250-484b3254-c37b-4f1a-a3c5-8228b7165b62.png)

**Comment by datacrystals** [comment] 2022-03-06 09:12
Try it now, should be fixed.

**Comment by kbooom1273** [comment] 2022-03-06 09:13
it work grid good

**Closed** 2022-03-06 09:13 UTC
